<a href="https://colab.research.google.com/github/mhmd2015/ImageProcessing1UIC/blob/main/Convolution-Correlation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

x = np.array([0,0,0.1,0.2,2,2.1,2,2.1,2, 2])
h = np.array([0.5, 0.5, 0.25])



In [29]:
# define the functions
def convolve_1d(signal, kernel):
    # Flip the kernel for convolution
    kernel = np.flip(kernel)

    # Lengths of input signal and kernel
    signal_len = len(signal)
    kernel_len = len(kernel)

    # Create an output array of the appropriate size
    output_len = signal_len + kernel_len - 1
    output = np.zeros(output_len)

    # Convolve signal with kernel
    for i in range(output_len):
        for j in range(kernel_len):
            if i - j >= 0 and i - j < signal_len:
                output[i] += signal[i - j] * kernel[j]

    return output

def convolve_1d_explain(signal, kernel):
    # Flip the kernel for convolution
    kernel = np.flip(kernel)

    # Lengths of input signal and kernel
    signal_len = len(signal)
    kernel_len = len(kernel)

    # Create an output array of the appropriate size
    output_len = signal_len + kernel_len - 1
    output = np.zeros(output_len)

    # Convolve signal with kernel
    for i in range(output_len):
        eq="";
        rs="";
        for j in range(kernel_len):
            if i - j >= 0 and i - j < signal_len:
              #print("i="+str(i)+",j="+str(j)+":output[i]="+str(output[i])+"    x(i-j) => x("+str((i-j))+")="+str(signal[i-j])+" *    h(j)=> h("+str(j)+")="+str(kernel[j]))
              #print("i="+str(i)+",j="+str(j)+":output[i]="+str(output[i])+"    x(i-j) * h(j) => x("+str((i-j))+") * h("+str(j)+") => "+str(signal[i-j])+" * "+str(kernel[j]))
              if(eq != ""):
                eq+=" + "
              eq+="x("+str((i-j))+") * h("+str(j)+")"

              if(rs != ""):
                rs+=" + "
              rs+=str(signal[i-j])+" * "+str(kernel[j])


              output[i] += signal[i - j] * kernel[j]
        #print("i="+str(i)+":output[i]=> y("+str(i)+")="+str(output[i]))
        print("y("+str(i)+") = "+eq+" => "+rs+" = "+str(output[i]))
    return output


def convolution_2d(image, filt):
  m, n = filt.shape
  if(m == n):
    y, x = image.shape
    y = y - m +1
    x = x - m +1
    new_image = np.zeros((x,y))
    for i in range(y):
      for j in range(x):
        new_image[i][j]=np.sum(image[i:i+m, j:j+m] * filt)
  return new_image


def correlate_1d(signal, kernel):
    # Lengths of input signal and kernel
    signal_len = len(signal)
    kernel_len = len(kernel)

    # Create an output array of the appropriate size
    output_len = signal_len + kernel_len - 1
    output = np.zeros(output_len)

    # Correlate signal with kernel
    for i in range(output_len):
        for j in range(kernel_len):
            if i - j >= 0 and i - j < signal_len:
                output[i] += signal[i - j] * kernel[j]

    return output

def correlate_1d_explain(signal, kernel):
    # Lengths of input signal and kernel
    signal_len = len(signal)
    kernel_len = len(kernel)

    # Create an output array of the appropriate size
    output_len = signal_len + kernel_len - 1
    output = np.zeros(output_len)

    # Correlate signal with kernel
    for i in range(output_len):
        eq="";
        rs="";
        for j in range(kernel_len):
            if i - j >= 0 and i - j < signal_len:

                if(eq != ""):
                  eq+=" + "
                eq+="x("+str((i-j))+") * h("+str(j)+")"

                if(rs != ""):
                  rs+=" + "
                rs+=str(signal[i-j])+" * "+str(kernel[j])

                output[i] += signal[i - j] * kernel[j]
        print("y("+str(i)+") = "+eq+" => "+rs+" = "+str(output[i]))

    return output



In [5]:
y = np.convolve(x, h)
print(y)

[0.    0.    0.025 0.1   0.625 1.575 2.05  2.05  2.05  2.025 1.5   0.5  ]


In [11]:
result = convolve_1d(x,h)
print(result)

[0.    0.    0.025 0.1   0.625 1.575 2.05  2.05  2.05  2.025 1.5   0.5  ]


In [30]:
result = convolve_1d_explain(x,h)
print(result)

y(0) = x(0) * h(0) => 0.0 * 0.25 = 0.0
y(1) = x(1) * h(0) + x(0) * h(1) => 0.0 * 0.25 + 0.0 * 0.5 = 0.0
y(2) = x(2) * h(0) + x(1) * h(1) + x(0) * h(2) => 0.1 * 0.25 + 0.0 * 0.5 + 0.0 * 0.5 = 0.025
y(3) = x(3) * h(0) + x(2) * h(1) + x(1) * h(2) => 0.2 * 0.25 + 0.1 * 0.5 + 0.0 * 0.5 = 0.1
y(4) = x(4) * h(0) + x(3) * h(1) + x(2) * h(2) => 2.0 * 0.25 + 0.2 * 0.5 + 0.1 * 0.5 = 0.65
y(5) = x(5) * h(0) + x(4) * h(1) + x(3) * h(2) => 2.1 * 0.25 + 2.0 * 0.5 + 0.2 * 0.5 = 1.625
y(6) = x(6) * h(0) + x(5) * h(1) + x(4) * h(2) => 2.0 * 0.25 + 2.1 * 0.5 + 2.0 * 0.5 = 2.55
y(7) = x(7) * h(0) + x(6) * h(1) + x(5) * h(2) => 2.1 * 0.25 + 2.0 * 0.5 + 2.1 * 0.5 = 2.575
y(8) = x(8) * h(0) + x(7) * h(1) + x(6) * h(2) => 2.0 * 0.25 + 2.1 * 0.5 + 2.0 * 0.5 = 2.55
y(9) = x(9) * h(0) + x(8) * h(1) + x(7) * h(2) => 2.0 * 0.25 + 2.0 * 0.5 + 2.1 * 0.5 = 2.55
y(10) = x(9) * h(1) + x(8) * h(2) => 2.0 * 0.5 + 2.0 * 0.5 = 2.0
y(11) = x(9) * h(2) => 2.0 * 0.5 = 1.0
[0.    0.    0.025 0.1   0.65  1.625 2.55  2.575 2.55 

In [31]:
result = correlate_1d_explain(x,h)
print(result)

y(0) = x(0) * h(0) => 0.0 * 0.5 = 0.0
y(1) = x(1) * h(0) + x(0) * h(1) => 0.0 * 0.5 + 0.0 * 0.5 = 0.0
y(2) = x(2) * h(0) + x(1) * h(1) + x(0) * h(2) => 0.1 * 0.5 + 0.0 * 0.5 + 0.0 * 0.25 = 0.05
y(3) = x(3) * h(0) + x(2) * h(1) + x(1) * h(2) => 0.2 * 0.5 + 0.1 * 0.5 + 0.0 * 0.25 = 0.15000000000000002
y(4) = x(4) * h(0) + x(3) * h(1) + x(2) * h(2) => 2.0 * 0.5 + 0.2 * 0.5 + 0.1 * 0.25 = 1.125
y(5) = x(5) * h(0) + x(4) * h(1) + x(3) * h(2) => 2.1 * 0.5 + 2.0 * 0.5 + 0.2 * 0.25 = 2.0999999999999996
y(6) = x(6) * h(0) + x(5) * h(1) + x(4) * h(2) => 2.0 * 0.5 + 2.1 * 0.5 + 2.0 * 0.25 = 2.55
y(7) = x(7) * h(0) + x(6) * h(1) + x(5) * h(2) => 2.1 * 0.5 + 2.0 * 0.5 + 2.1 * 0.25 = 2.5749999999999997
y(8) = x(8) * h(0) + x(7) * h(1) + x(6) * h(2) => 2.0 * 0.5 + 2.1 * 0.5 + 2.0 * 0.25 = 2.55
y(9) = x(9) * h(0) + x(8) * h(1) + x(7) * h(2) => 2.0 * 0.5 + 2.0 * 0.5 + 2.1 * 0.25 = 2.525
y(10) = x(9) * h(1) + x(8) * h(2) => 2.0 * 0.5 + 2.0 * 0.25 = 1.5
y(11) = x(9) * h(2) => 2.0 * 0.25 = 0.5
[0.    0.  

In [35]:
def histogram(image):


  # Step 1: Compute histogram
  hist, bins = np.histogram(image.flatten(), bins=256, range=[0,256])

  # Step 2: Compute CDF
  cdf = hist.cumsum()
  cdf_normalized = cdf * hist.max() / cdf.max()

  # Normalize the CDF to fit in the 0-255 range
  cdf_m = np.ma.masked_equal(cdf,0)
  cdf_m = (cdf_m - cdf_m.min()) * 255 / (cdf_m.max()-cdf_m.min())
  cdf = np.ma.filled(cdf_m,0).astype('uint8')

  # Step 3: Use the CDF to equalize the image
  equalized_image = cdf[image]

  return equalized_image

In [36]:
image = np.array([
    [5,  6,  5,  5,  5],
    [4, 99,  5,  5,  5],
    [4,  5,  5,  5,  5],
    [5,  5,  6,  6,  6],
    [5,  4,  5,  4, 44]
  ])

result = histogram(image)
print(result)

[[182 230 182 182 182]
 [  0 255 182 182 182]
 [  0 182 182 182 182]
 [182 182 230 230 230]
 [182   0 182   0 242]]
