<a href="https://colab.research.google.com/github/mhmd2015/ImageProcessing1UIC/blob/main/DIP_UIC_Week3_DiscreteCosineTransformDCT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import cv2



In [10]:
# Define the toy image
x = np.array([[1, 1],
              [1, 1]], dtype=np.float32)

# Compute the DCT
dct_result = cv2.dct(x)

print(dct_result)

[[1.9999999e+00 0.0000000e+00]
 [2.5376103e-08 0.0000000e+00]]


In [13]:


def compute_dct(img):
    M, N = img.shape
    X = np.zeros((M, N))

    # Scale factors
    C = lambda x: 1/np.sqrt(2) if x == 0 else 1

    for u in range(M):
        for v in range(N):
            sum_val = 0
            for m in range(M):
                for n in range(N):
                    sum_val += img[m, n] * np.cos((np.pi * (2*m + 1) * u) / (2 * M)) * np.cos((np.pi * (2*n + 1) * v) / (2 * N))
            X[u, v] = C(u) * C(v) * sum_val
            #X[u, v] =  sum_val
    return X



In [23]:
def dct_2d(img):
    M, N = img.shape
    dct_result = np.zeros((M, N))

    # Scale factors
    C = lambda s: np.sqrt(1.0 / M) if s == 0 else np.sqrt(2.0 / M)

    for u in range(M):
        for v in range(N):
            sum_val = 0
            for m in range(M):
                for n in range(N):
                    sum_val += img[m, n] * np.cos((np.pi * (2*m + 1) * u) / (2 * M)) * np.cos((np.pi * (2*n + 1) * v) / (2 * N))
            dct_result[u, v] = C(u) * C(v) * sum_val

    return dct_result

In [25]:
def dct(image):

  dct_matrix = np.zeros((image.shape[0], image.shape[1]))

  for i in range(image.shape[0]):
    for j in range(image.shape[1]):
      dct_matrix[i, j] = (1 / np.sqrt(2)) * np.sum(
          image[i, :] * np.cos((2 * j + 1) * i * np.pi / 2))

  return dct_matrix

In [26]:
# Define the toy image
#img = np.array([[1, 1],[1, 1]])
img = np.mat("1 1 ; 1 1")

# Compute the 2x2 DCT
dct_result = compute_dct(img)
print(dct_result)

dct_result = dct_2d(img)
print(dct_result)

dct_result = dct(img)
print(dct_result)

[[2.00000000e+00 1.57009246e-16]
 [1.57009246e-16 0.00000000e+00]]
[[2.00000000e+00 1.57009246e-16]
 [1.57009246e-16 0.00000000e+00]]
[[ 1.41421356e+00  1.41421356e+00]
 [ 8.65956056e-17 -2.59786817e-16]]


In [28]:
from scipy.fftpack import fft, dct
import numpy as np
fft(np.array([1., 1., 1., 1.])).real

array([4., 0., 0., 0.])

In [29]:
dct(np.array([1., 1., 1., 1.]), 1)

array([6., 0., 0., 0.])

In [30]:
dct(np.array([1., 1., 1., 1.]), 2)

array([8., 0., 0., 0.])

In [31]:
dct(np.array([1., 1., 1., 1., 1., 1., 1., 1., 1.]), 2)

array([18.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [34]:
dct(np.array([1., 1., 1., 1.]), 1)

array([6., 0., 0., 0.])

In [35]:
dct(np.array([1., 1., 1., 1.]), 2)

array([8., 0., 0., 0.])

In [36]:
dct(np.array([1., 1., 1., 1.]), 3)

array([ 5.02733949, -1.49660576,  0.66817864, -0.19891237])

In [37]:
dct(np.array([1., 1., 1., 1.]), 4)

array([ 5.1258309 , -1.79995245,  1.20268977, -1.01959116])