<a href="https://colab.research.google.com/github/mhmd2015/ImageProcessing1UIC/blob/main/EigenVector_covariance1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
A = np.mat("1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16")
print("A:\n",A)

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Run Eigen Vector

In [8]:
eigvals = np.linalg.eigvals(A)
print("Eigen Value:\n",eigvals)

Eigen Value:
 [ 3.62093727e+01 -2.20937271e+00 -2.62410379e-15 -9.51420961e-17]


In [7]:
eigvals , eigvector = np.linalg.eig(A)
print("Eigen Value:\n",eigvals)
print("Eigen Vector:\n",eigvector)

Eigen Value:
 [ 3.62093727e+01 -2.20937271e+00 -2.62410379e-15 -9.51420961e-17]
Eigen Vector:
 [[-0.15115432 -0.72704996 -0.47688035 -0.07702174]
 [-0.34923733 -0.28320876  0.83665151 -0.30149603]
 [-0.54732033  0.16063243 -0.24266197  0.83405728]
 [-0.74540333  0.60447363 -0.11710919 -0.45553951]]


Let's start from vector to find the covariance matrix
1- define vector (vec)
2- the the mean (m)
3- decrease the vec from m to generate to new matrix (aa)
4- apply exp 2 on the aa

In [13]:
vec = np.array([1,2,3,4])
print("Vector:\n",vec)

Vector:
 [1 2 3 4]


In [14]:
m = np.mean(vec)
print("mean:\n",m)

mean:
 2.5


In [16]:
# to find the covariance matrix
aa = vec - m

#cov = aa * aa
cov = np.outer(aa,aa)


print("covariance matrix:\n",cov)

covariance matrix:
 [[ 2.25  0.75 -0.75 -2.25]
 [ 0.75  0.25 -0.25 -0.75]
 [-0.75 -0.25  0.25  0.75]
 [-2.25 -0.75  0.75  2.25]]
